#2 Place a marble on the board
marmelab/pentago-python pull request #3
Opened 2021-01-25 16:20 UTC by Clebiez

# (0.25) As Brice, I can place a marble on the board

- [x] Adding user input to place a marble
- [x] Check if user input is correct
- [x] Place marble in case of correct input
- [x] If board is full, stop the game

![Peek 2021-01-25 17-17](https://user-images.githubusercontent.com/12797391/105733073-6657d300-5f31-11eb-87c1-38b192f2b01e.gif)

2021-01-25 16:45 UTC, fzaninotto requested changes

2021-01-25 16:45 UTC, fzaninotto commented on src/board.py
> +        y = ord(position[0].lower()) - 97
that's cryptic, and I don't want to go to StackOveflow to understand. Would you mind explaining here?

2021-01-25 16:45 UTC, fzaninotto commented on src/board.py
> +def get_position_if_valid(board, position):
I don't understand the code of this method. Perhaps you could detail the input format and add comments?

2021-01-25 16:45 UTC, fzaninotto commented on src/test_board.py
> +    def test_get_position_if_valid_should_return_array_position(self):
A good practice is to have 1 assertion per test. I suggest you use test providers (I don't know how they are called in Python, but it's a set of data you run your test on)

2021-01-25 16:45 UTC, fzaninotto commented on src/test_board.py
> +        print_board(board)
only in verbose mode

2021-01-25 16:45 UTC, fzaninotto commented on src/test_board.py
> +        expected_board[0][0] = 1
a bit weak, you test only the easiest position

2021-01-25 16:47 UTC, HALLERPierre commented on src/board.py
> +        return [x, y]
I think you should use a tuple for that because it's fixed size and it should be immutable

2021-01-25 16:47 UTC, HALLERPierre commented on src/board.py
> +        r = range(0, 6)
Why 6 ? If it's the size of the board I think you should use at least a named const so you can change it easily if needed or asked

2021-01-25 16:47 UTC, HALLERPierre commented on src/board.py
> +    board[position[0]][position[1]] = 1
Careful board is muted here, maybe deep clone it before that

2021-01-25 21:36 UTC, fzaninotto approved these changes

2021-01-26 09:12 UTC, mchaffotte approved these changes

2021-01-26 09:12 UTC, mchaffotte commented on src/constant.py
> +ARRAY_SIZE = 6
array is too generic imo -> board_size ?

2021-01-26 09:12 UTC, merged